# Generated by Django 5.0.4 on 2024-09-02 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_recipeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.inventory'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='RecipeItem',
        ),
    ]
