# Generated by Django 5.0.4 on 2024-09-20 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_recipeitem_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
