# Generated by Django 5.0.4 on 2024-09-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_standardinventory_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardinventory',
            name='code',
            field=models.CharField(default=1, max_length=15),
        ),
        migrations.AddField(
            model_name='standardinventory',
            name='location',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
