# Generated by Django 5.0.4 on 2024-09-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_standardinventory_code_standardinventory_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardinventory',
            name='code',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='standardinventory',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='standardinventory',
            name='price_per_unit',
            field=models.FloatField(default=''),
        ),
    ]
