# Generated by Django 5.0.4 on 2024-09-22 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_inventory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_location', to='app.standardinventory'),
        ),
    ]
